site_name: RackShift 文档
theme:
  name: 'material'
  logo: 'img/logo.png'
  favicon: 'img/favicon.png'
  language: 'zh'
  highlightjs: true
  hljs_languages:
    - yaml
    - django
  custom_dir: 'theme'
nav:
  - 介绍: index.md
  - 快速开始: quick_start.md
  - 使用方法:
      - 准备工作: config.md
      - 初始化物理机(以DELL为例): dell.md
      - 发现物理机: discovery.md
      - 物理机生命周期: lifecycle.md
      - 执行工作流: workflow.md
      - 安装 WindowsServer 2012/2016/2019: windows.md
      - 安装 Ubuntu 18.04: ubuntu.md
      - 安装 Ubuntu 20.04: ubuntu-20.04.md
      - 常用 ISO: iso.md
      - 使用插件: plugin.md
      - Post-Install 脚本: post-install.md
      - WEBKVM 远程控制台: webkvm.md
  - 系统架构: structure.md
  - 网络结构: network.md
  - 深入内部:
      - 术语: theory.md
      - RackShift 对 RackHD 的扩展: extend.md
      - 端口释义: port.md
  - 故障排除: faq.md
  #  - 开发手册: dev.md
  - 联系我们: about.md


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: True
      linenums: False
  - toc:
      permalink: True
  - footnotes
  - attr_list
  - def_list
  - tables
  - abbr
  - md_in_html
  - pymdownx.extra
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.progressbar


extra_css:
  - css/extra.css

copyright: Copyright &copy; 2014-2020 <a href="https://www.fit2cloud.com">杭州飞致云信息科技有限公司</a>, All Rights Reserved. <a href="http://www.beian.miit.gov.cn" target="_blank">京ICP备15023818号</a>

plugins:
  - search
#  - pdf-export:
#      verbose: true
#      media_type: print
#      enabled_if_env: ENABLE_PDF_EXPORT2

extra:
  version:
    method: mike