site_name: RackShift 文档
theme:
  name: 'material'
nav:
  - 介绍: index.md
  - 快速开始: quick_start.md
  - 系统架构: structure.md
  - 部署您的第一台物理机: deploy_first.md
  - 执行工作流: workflow.md
  - 故障排除: faq.md
  - 开发手册: dev.md
  - 关于: about.md


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: True
      linenums: False
  - toc:
      permalink: True
  - footnotes
  - attr_list
  - def_list
  - tables
  - abbr
  - md_in_html
  - pymdownx.extra
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.progressbar

extra_css:
  - css/extra.css

copyright: Copyright &copy; 2014-2020 <a href="https://www.fit2cloud.com">杭州飞致云信息科技有限公司</a>, All Rights Reserved. <a href="http://www.beian.miit.gov.cn" target="_blank">京ICP备15023818号</a>

plugins:
  - search