site_name: RackShift 文档
theme:
  name: 'material'
nav:
  - 介绍: index.md
  - 快速开始: quick_start.md
  - 系统架构: structure.md
  - 部署您的第一台物理机: deploy_first.md
  - 执行工作流: workflow.md
  - 故障排除: faq.md
  - 开发手册: dev.md
  - 关于: about.md

